dia = input('Dia = ')
mes = input('Mês = ')
ano = input('Ano = ')
print('Você nasceu no dia', dia, 'de', mes, 'de', ano + ',' ' certo?')
#nome = input('Qual é o seu nome? ')
#print('Boas vindas {}, como vai?'.format(nome))