a = input('Digite algo ai meu irmão: ')
print('O tipo primitivo dele é:', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É uma letra?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('È um décimal?', a.isdecimal())
print('É minusculo?', a.islower())
print('É maiusculo?', a.isupper())
print('É capitalizada?', a.istitle())
